name: skybook
description: A simple flight logbook app built with Flutter.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  flutter_map: ^6.1.0
  latlong2: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
